jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: ['3.7']
    steps:
    # python
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install Dependencies
        run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # R
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      # Renv
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2
      # pandoc
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1' # The pandoc version to download (if necessary) and use.
      # tinytex
      - uses: r-lib/actions/setup-tinytex@v2
      # Run Snakemake
      - name: Run Snakemake
        run: snakemake all --cores 1